POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer tokenHere

{
    "title": "Title of some blog",
    "author": "Author some of blog",
    "url": "Url of some blog",
    "likes": 1
}
